Create MER-2.txt
gandhiayush/demo_repo pull request #10
Opened 2024-10-24 08:28 UTC by gandhiayush

MER-2 added

2024-10-24 09:05 UTC, closed without merging

2024-10-24 10:03 UTC, gandhiayush commented
new comment

2024-10-24 10:14 UTC, gandhiayush commented
ok

2024-10-24 10:22 UTC, gandhiayush commented
ddsa

2024-10-24 10:22 UTC, gandhiayush commented
ok

2024-10-24 10:24 UTC, gandhiayush commented
okookokokok

2024-10-24 10:26 UTC, gandhiayush commented
ok

2024-10-24 10:29 UTC, gandhiayush commented
nice

2024-10-24 11:17 UTC, gandhiayush commented
ok

2024-10-24 11:18 UTC, gandhiayush commented
ok

2024-10-24 11:22 UTC, gandhiayush commented
okk

2024-10-24 11:27 UTC, gandhiayush commented
ok

2024-10-24 11:28 UTC, jMakadiya commented
Hello Ayush,

 Any update on review changes ?

2024-10-24 11:30 UTC, jMakadiya requested changes

2024-10-24 11:30 UTC, jMakadiya commented on MER-2.txt
> +MER-2
Hello Ayush

2024-10-24 11:39 UTC, gandhiayush commented on MER-2.txt
> +MER-2
ok

2024-10-24 11:42 UTC, gandhiayush commented on MER-2.txt
> +MER-2
hello

2024-10-25 05:41 UTC, gandhiayush commented
nice comment

2024-10-25 05:41 UTC, gandhiayush commented on MER-2.txt
> +MER-2
**done**